USE ardetho_erp;

ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS cargo VARCHAR(100) NULL AFTER email,
  ADD COLUMN IF NOT EXISTS departamento VARCHAR(100) NULL AFTER cargo;

CREATE TABLE IF NOT EXISTS configuracoes (
  chave VARCHAR(80) NOT NULL,
  valor TEXT NOT NULL,
  data_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (chave)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
